// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUtXSnhRYzJ5MjVUWGVqaGJmRHh2QlpFcWVBa2x3bGJCWm9VY1lXakVYZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0dDeWx1UklKUnlxZE1aek9KcEM5NUwzSXNPMzRWZXUxSENrSFd4WDF6Zz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRQThyNlAybGdFck1RSDU1cWMvSmJSQUFGZ0pBREZudGl4aCtyRkxnMzJRPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI5YW1lNEVtNElyZDNzYzY3eFQwRmtJVnFEbVRLQ2tOKzB1UDRuTmlIZEc0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtBZ08rRHJlUlFoQzEzaW1mU2ZvWUNNckFDalpRZFhOVUFvem5EQmFlRWM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkhxbU9qWnB6UXlBY0syaEZIcTdrcWJMRkxqd2syYnAyUzk5NVl2U2xORU09In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicUlBRXB3Y3JteUVvR1lHN2I3WFBDMW83aFlXOU91MUNmNDAwcXlGbUpXMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTDl4N2pTd3pjSGdSaFdFQ3NYSzFCWGlMMlJZbW83OEZ1cUZzS2RjN0FoVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik5vODNNaStsQ3FveU02UlZKSWRPMnJEbllwd21TbXU4a0o3T0p6dTB3RTNYMExEUlR3b2R0VTJIZ2M5WTliVGJ1dGtRZGlBem4vVHZ4c3ArMjBoNUJBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjAwLCJhZHZTZWNyZXRLZXkiOiJxTnpnTnRjdGM4ZTJZL21QVVNlcVZTVjMwcW9jYzI1NTFGOWlxaW5hUUY0PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJlcUhOeU96alRVT2IyTkM0TUpJLWdnIiwicGhvbmVJZCI6IjU0YzEyYzUyLTk5ZTEtNDU1Ny05MDlhLWIyNmE1YjQwOWNiNCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJEekRHU1pZWHBrL1BUbkpkWDF4VTJWMUdVZVU9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibmF5S2JEYjdDWEU4bDBCS3pJZGR6NWt3OXpJPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkFIU0U4V0xXIiwibWUiOnsiaWQiOiIyMzQ3MDY2NTA2ODk5OjY2QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IkFjdGl2ZSBBZG1pbiJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTlQ3ayt3QkVKR1M0cmdHR0F3Z0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiVkNMWUlBSDErazVrK1QxQTZlYUVDZ1I1aEtQNUJ4dVR0SjY0aFVSdG9XOD0iLCJhY2NvdW50U2lnbmF0dXJlIjoiSUdLbXZQSG90ekxVcG02Tm5vV2N4UEJNbGRlaDN2U2tlU2JxcXM1Q0dYZW5qelRrU2FZNVBlU3JOUVBVdmU3WDg5bWp6eXdrY2N1M1l1cW5lU0VPQ2c9PSIsImRldmljZVNpZ25hdHVyZSI6ImhDbVFJR2VKSFkvNmx6clE3VzJpL1EwN2NXbGNmek10dmh3a2g3eVkxdEUreFgyb3ByMmxKUGtTSFZiWVVRWVJzR3pQaVpWTThrNVpMQlR5QzhiWERBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0NzA2NjUwNjg5OTo2NkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJWUWkyQ0FCOWZwT1pQazlRT25taEFvRWVZU2orUWNiazdTZXVJVkViYUZ2In19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzI5NjYxMjEzLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUI3MiJ9",
  PREFIX: process.env.PREFIX || '.',
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "Bera",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "254743982206",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
